import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@clerk/nextjs/server'
import { clerkClient } from '@clerk/nextjs/server'
import { ConvexHttpClient } from 'convex/browser'
import { api } from '@/convex/_generated/api'

const convex = new ConvexHttpClient(process.env.NEXT_PUBLIC_CONVEX_URL!)

/**
 * POST /api/users/sync
 * Manually sync all users from Clerk to Convex
 * This is useful when webhooks aren't working or users are missing
 */
export async function POST(request: NextRequest) {
  try {
    // Verify authentication - only allow admins
    const { userId } = await auth()
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Get Clerk client
    const client = await clerkClient()
    
    // Fetch all users from Clerk (paginate through all users)
    let allClerkUsers: any[] = []
    let hasMore = true
    let offset = 0
    const limit = 500
    
    while (hasMore) {
      const response = await client.users.getUserList({ limit, offset })
      allClerkUsers = [...allClerkUsers, ...response.data]
      hasMore = response.data.length === limit
      offset += limit
    }
    
    let synced = 0
    let errors = 0
    const errorDetails: string[] = []

    // Sync each user to Convex
    for (const clerkUser of allClerkUsers) {
      try {
        // Check if user already exists in Convex to preserve their role and branch
        const existingUser = await convex.query(api.users.getUserByClerkId, {
          clerkId: clerkUser.id,
        })
        
        // Build the mutation args - only include role for new users
        const mutationArgs: any = {
          clerkId: clerkUser.id,
          firstName: clerkUser.firstName || undefined,
          lastName: clerkUser.lastName || undefined,
          email: clerkUser.emailAddresses[0]?.emailAddress || '',
          imageUrl: clerkUser.imageUrl || undefined,
          isAutoGenerated: false,
        }
        
        // Only set role for new users (preserve existing role for existing users)
        if (!existingUser) {
          mutationArgs.role = 'staff' // Default role for new users
        } else {
          // Preserve existing role and branches for existing users
          // Don't pass role - upsertUser will preserve it
          if (existingUser.branchIds) {
            mutationArgs.branchIds = existingUser.branchIds
          }
        }
        
        await convex.mutation(api.users.upsertUser, mutationArgs)
        synced++
      } catch (error) {
        errors++
        errorDetails.push(`Failed to sync user ${clerkUser.id}: ${error instanceof Error ? error.message : 'Unknown error'}`)
        console.error(`Failed to sync user ${clerkUser.id}:`, error)
      }
    }

    return NextResponse.json({
      success: true,
      message: `Synced ${synced} users. ${errors} errors.`,
      synced,
      errors,
      total: allClerkUsers.length,
      errorDetails: errors > 0 ? errorDetails : undefined,
    })
  } catch (error) {
    console.error('Error syncing users:', error)
    return NextResponse.json(
      {
        error: 'Failed to sync users',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    )
  }
}
