import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

export default defineSchema({
  users: defineTable({
    clerkId: v.string(),
    firstName: v.optional(v.string()),
    lastName: v.optional(v.string()),
    email: v.string(),
    imageUrl: v.optional(v.string()),
    bio: v.optional(v.string()),
    role: v.optional(v.string()), // User role for permissions: 'super_admin', 'admin', or 'staff'
    branchId: v.optional(v.id('branches')), // Assigned branch
    createdAt: v.number(),
    updatedAt: v.number(),
    lastSignInAt: v.optional(v.number()),
    isAutoGenerated: v.optional(v.boolean()), // Track if user was auto-generated
  })
    .index('by_clerk_id', ['clerkId'])
    .index('by_email', ['email'])
    .index('by_created_at', ['createdAt'])
    .index('by_auto_generated', ['isAutoGenerated'])
    .index('by_role', ['role'])
    .index('by_branch_id', ['branchId']),
  
  temporaryReceipts: defineTable({
    docNo: v.string(),
    docDate: v.string(), // ISO date string
    paymentDate: v.string(), // ISO date string (renamed from dueDate)
    debtorCode: v.string(),
    description: v.optional(v.string()),
    salesAgent: v.optional(v.string()),
    currencyCode: v.string(),
    currencyRate: v.number(),
    toTaxCurrencyRate: v.number(),
    total: v.optional(v.number()),
    localTotal: v.optional(v.number()),
    tax: v.optional(v.number()),
    localTax: v.optional(v.number()),
    netTotal: v.optional(v.number()),
    localNetTotal: v.optional(v.number()),
    paymentAmt: v.optional(v.number()),
    localPaymentAmt: v.optional(v.number()),
    outstanding: v.optional(v.number()),
    cancelled: v.string(), // 'Y' or 'N'
    docStatus: v.string(), // 'O' for Open, 'C' for Closed, etc.
    inclusiveTax: v.string(), // 'Y' or 'N'
    roundingMethod: v.number(),
    withholdingTaxVersion: v.number(),
    withholdingTaxRoundingMethod: v.number(),
    lastModified: v.string(), // ISO date string
    lastModifiedUserID: v.string(),
    createdTimeStamp: v.string(), // ISO date string
    createdUserID: v.string(),
    createdByName: v.optional(v.string()), // Display name of creator
    paymentMethod: v.optional(v.string()), // Payment method (Cash, Bank Transfer, etc.)
    priceCharge: v.optional(v.number()), // Price to charge
    priceReceive: v.optional(v.number()), // Price received
    remark: v.optional(v.string()), // Additional remarks
    branchId: v.optional(v.id('branches')), // Branch that created this receipt
  })
    .index('by_doc_no', ['docNo'])
    .index('by_debtor_code', ['debtorCode'])
    .index('by_doc_date', ['docDate'])
    .index('by_status', ['cancelled', 'docStatus'])
    .index('by_created_at', ['createdTimeStamp'])
    .index('by_branch_id', ['branchId']),
  
  temporaryReceiptLineItems: defineTable({
    receiptId: v.id('temporaryReceipts'),
    seq: v.number(),
    accNo: v.optional(v.string()),
    toAccountRate: v.number(),
    description: v.optional(v.string()),
    projNo: v.optional(v.string()),
    deptNo: v.optional(v.string()),
    taxCode: v.optional(v.string()),
    tax: v.optional(v.number()),
    localTax: v.optional(v.number()),
    amount: v.optional(v.number()),
    netAmount: v.optional(v.number()),
    localNetAmount: v.optional(v.number()),
    taxableAmt: v.optional(v.number()),
    subTotal: v.optional(v.number()),
    localSubTotal: v.optional(v.number()),
    taxRate: v.optional(v.number()),
  })
    .index('by_receipt_id', ['receiptId'])
    .index('by_receipt_seq', ['receiptId', 'seq']),
  
  branches: defineTable({
    branchName: v.string(),
    alias: v.optional(v.string()), // Display name for tabs (optional)
    doNumbering: v.optional(v.string()), // Prefix only (e.g., "SOTP1" not "SOTP1-000001")
    trNumbering: v.optional(v.string()), // Prefix only for Temporary Receipts (e.g., "TR1")
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_created_at', ['createdAt']),
  
  // Mapping table to track which branch each delivery order belongs to
  // Delivery orders are stored in AutoCount, but we track branch assignment here
  deliveryOrderBranches: defineTable({
    docKey: v.number(), // AutoCount DocKey
    docNo: v.string(), // AutoCount DocNo
    branchId: v.id('branches'), // Branch that created this delivery order
    createdAt: v.number(),
  })
    .index('by_doc_key', ['docKey'])
    .index('by_doc_no', ['docNo'])
    .index('by_branch_id', ['branchId']),
  
  // Product templates for branches - pre-set items for DO creation
  branchProductTemplates: defineTable({
    branchId: v.id('branches'),
    itemCode: v.string(), // Product ItemCode
    nricTaxCode: v.optional(v.string()), // Tax code for NRIC customers
    passportTaxCode: v.optional(v.string()), // Tax code for Passport customers
    defaultQty: v.optional(v.number()), // Default quantity
    defaultPrice: v.optional(v.number()), // Default price
    seq: v.number(), // Display order
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('by_branch_id', ['branchId'])
    .index('by_branch_item', ['branchId', 'itemCode']),
  
  // Stock keeping - independent from AutoCount (legacy; prefer stockBalances per branch)
  stockKeeping: defineTable({
    itemCode: v.string(), // Product ItemCode
    quantity: v.number(), // Current stock quantity
    location: v.optional(v.string()), // Location (optional)
    lastUpdated: v.number(),
    lastUpdatedBy: v.string(), // User ID who last updated
    lastMovementType: v.optional(v.string()), // e.g. DO_OUT, DO_VOID_IN, ADJUSTMENT
    lastMovementDelta: v.optional(v.number()), // e.g. -5 or +10
    notes: v.optional(v.string()),
  })
    .index('by_item_code', ['itemCode'])
    .index('by_location', ['location']),

  // Per-branch stock balances (Phase 1 full stock keeping)
  stockBalances: defineTable({
    branchId: v.id('branches'),
    itemCode: v.string(),
    quantityOnHand: v.number(),
    quantityReserved: v.optional(v.number()), // Optional; 0 if not used
    lastMovementAt: v.number(),
    lastMovementBy: v.string(),
    remarks: v.optional(v.string()),
  })
    .index('by_branch', ['branchId'])
    .index('by_branch_item', ['branchId', 'itemCode']),

  // Stock movement audit trail
  stockMovements: defineTable({
    branchId: v.id('branches'),
    itemCode: v.string(),
    quantityDelta: v.number(),
    quantityAfter: v.number(),
    movementType: v.string(),
    referenceType: v.optional(v.string()),
    referenceId: v.optional(v.string()),
    userId: v.string(),
    createdAt: v.number(),
    notes: v.optional(v.string()),
  })
    .index('by_branch', ['branchId'])
    .index('by_branch_item', ['branchId', 'itemCode'])
    .index('by_branch_created', ['branchId', 'createdAt'])
    .index('by_reference', ['referenceType', 'referenceId']),

  // Per-item movement logs (global stock) — in/out with notes, time, reference
  stockMovementLogs: defineTable({
    itemCode: v.string(),
    quantityDelta: v.number(),
    quantityAfter: v.number(),
    movementType: v.string(),
    referenceType: v.optional(v.string()),
    referenceId: v.optional(v.string()),
    userId: v.string(),
    createdAt: v.number(),
    notes: v.optional(v.string()),
  })
    .index('by_item_code', ['itemCode'])
    .index('by_item_created', ['itemCode', 'createdAt']),
})
