import { NextRequest, NextResponse } from 'next/server'
import { ConvexHttpClient } from 'convex/browser'
import { api } from '@/convex/_generated/api'
import { Webhook } from 'svix'

// Initialize Convex client only at runtime
let convex: ConvexHttpClient | null = null

function getConvexClient(): ConvexHttpClient {
  if (!convex) {
    const url = process.env.NEXT_PUBLIC_CONVEX_URL
    if (!url) {
      throw new Error('NEXT_PUBLIC_CONVEX_URL environment variable is not set')
    }
    convex = new ConvexHttpClient(url)
  }
  return convex
}

// Verify webhook signature using Svix
function verifyWebhookSignature(payload: string, headers: Record<string, string>, secret: string): any {
  const svix = new Webhook(secret)
  return svix.verify(payload, headers)
}

// GET endpoint to test if webhook route is accessible
export async function GET(request: NextRequest) {
  return NextResponse.json({
    message: 'Clerk webhook endpoint is accessible',
    endpoint: '/api/webhooks/clerk',
    method: 'POST',
    requiredHeaders: ['svix-signature', 'svix-timestamp', 'svix-id'],
    configured: !!process.env.CLERK_WEBHOOK_SECRET,
  })
}

export async function POST(request: NextRequest) {
  const webhookId = request.headers.get('svix-id') || 'unknown'
  console.log(`[Webhook] Received webhook request: ${webhookId}`)
  
  try {
    const body = await request.text()
    const signature = request.headers.get('svix-signature') || ''
    const timestamp = request.headers.get('svix-timestamp') || ''
    const id = request.headers.get('svix-id') || ''

    console.log(`[Webhook] Headers received - ID: ${id}, Timestamp: ${timestamp}, Signature: ${signature ? 'present' : 'missing'}`)

    // Verify webhook signature using Svix
    if (!process.env.CLERK_WEBHOOK_SECRET) {
      console.error('[Webhook] CLERK_WEBHOOK_SECRET is not set')
      return NextResponse.json(
        { error: 'Webhook secret not configured' },
        { status: 500 }
      )
    }

    try {
      const event = verifyWebhookSignature(body, {
        'svix-signature': signature,
        'svix-timestamp': timestamp,
        'svix-id': id,
      }, process.env.CLERK_WEBHOOK_SECRET)
      
      const { type, data } = event
      console.log(`[Webhook] Processing event type: ${type}`)
      console.log(`[Webhook] Event data keys:`, Object.keys(data || {}))
      console.log(`[Webhook] User ID: ${data.id || data.user_id || 'N/A'}`)

      // Process webhook events
      switch (type) {
        case 'user.created':
          // Sync new user to Convex
          try {
            console.log(`[Webhook] Creating user in Convex: ${data.id}`)
            await getConvexClient().mutation(api.users.upsertUser, {
              clerkId: data.id,
              firstName: data.first_name || undefined,
              lastName: data.last_name || undefined,
              email: data.email_addresses?.[0]?.email_address || data.email_addresses?.[0]?.emailAddress || '',
              imageUrl: data.image_url || undefined,
              role: 'staff', // Default role for new users
              isAutoGenerated: false, // Mark as webhook-created user
            })
            console.log(`[Webhook] ✓ User created and synced successfully: ${data.id}`)
          } catch (error) {
            console.error(`[Webhook] ✗ Failed to sync user ${data.id}:`, error)
            throw error // Re-throw to ensure webhook returns error status
          }
          break

        case 'user.updated':
          // Update user in Convex (preserve existing role if user already exists)
          await getConvexClient().mutation(api.users.upsertUser, {
            clerkId: data.id,
            firstName: data.first_name,
            lastName: data.last_name,
            email: data.email_addresses[0]?.email_address || '',
            imageUrl: data.image_url,
            // Note: role is not updated here to preserve existing role assignments
            isAutoGenerated: false, // Mark as webhook-created user
          })
          console.log(`User updated: ${data.id}`)
          break

        case 'user.deleted':
          // Remove user from Convex
          await getConvexClient().mutation(api.users.deleteUserByClerkId, {
            clerkId: data.id,
          })
          console.log(`User deleted: ${data.id}`)
          break

        case 'session.created':
          // Update last sign in when user signs in
          // Clerk session.created event structure: { user_id, session_id, ... }
          // Note: session.created might not have user_id in all cases, so we handle it gracefully
          try {
            const userId = data.user_id || (data as any).userId || (data as any).id
            if (userId && typeof userId === 'string') {
              console.log(`[Webhook] Updating last sign in for user: ${userId}`)
              await getConvexClient().mutation(api.users.updateLastSignIn, {
                clerkId: userId,
              })
              console.log(`[Webhook] ✓ Session created and last sign in updated for user: ${userId}`)
            } else {
              console.warn(`[Webhook] session.created event missing valid user_id (got: ${userId}), skipping last sign in update`)
            }
          } catch (error) {
            console.error(`[Webhook] ✗ Failed to update last sign in:`, error)
            // Don't throw - session.created is not critical for user sync
            // Log the error but continue processing
          }
          break

        default:
          console.log(`Unhandled webhook type: ${type}`)
      }

      console.log(`[Webhook] ✓ Successfully processed event: ${type}`)
      return NextResponse.json({ success: true, eventType: type, webhookId: id })
      
    } catch (verificationError) {
      console.error('[Webhook] ✗ Signature verification failed:', verificationError)
      return NextResponse.json(
        { 
          error: 'Invalid webhook signature',
          details: verificationError instanceof Error ? verificationError.message : 'Unknown error',
          webhookId: id
        },
        { status: 401 }
      )
    }

  } catch (error) {
    console.error('[Webhook] ✗ Processing error:', error)
    return NextResponse.json(
      { 
        error: 'Webhook processing failed',
        details: error instanceof Error ? error.message : 'Unknown error',
        webhookId: webhookId
      },
      { status: 500 }
    )
  }
}
